/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardApproachRouteImport } from './routes/dashboard.approach'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard.community'
import { Route as DashboardExplorerRouteImport } from './routes/dashboard.explorer'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved'
import { Route as DashboardSearchRouteImport } from './routes/dashboard.search'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as DashboardTestClassroomIdTestIdRouteImport } from './routes/dashboard.test.$classroomId.$testId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApproachRoute = DashboardApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExplorerRoute = DashboardExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSearchRoute = DashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTestClassroomIdTestIdRoute =
  DashboardTestClassroomIdTestIdRouteImport.update({
    id: '/test/$classroomId/$testId',
    path: '/test/$classroomId/$testId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/approach': typeof DashboardApproachRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/explorer': typeof DashboardExplorerRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/test/$classroomId/$testId': typeof DashboardTestClassroomIdTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/approach': typeof DashboardApproachRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/explorer': typeof DashboardExplorerRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/test/$classroomId/$testId': typeof DashboardTestClassroomIdTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/approach': typeof DashboardApproachRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/explorer': typeof DashboardExplorerRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/search': typeof DashboardSearchRoute
  '/dashboard/teacher': typeof DashboardTeacherRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/test/$classroomId/$testId': typeof DashboardTestClassroomIdTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/dashboard/approach'
    | '/dashboard/community'
    | '/dashboard/explorer'
    | '/dashboard/history'
    | '/dashboard/saved'
    | '/dashboard/search'
    | '/dashboard/teacher'
    | '/dashboard/'
    | '/dashboard/test/$classroomId/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/dashboard/approach'
    | '/dashboard/community'
    | '/dashboard/explorer'
    | '/dashboard/history'
    | '/dashboard/saved'
    | '/dashboard/search'
    | '/dashboard/teacher'
    | '/dashboard'
    | '/dashboard/test/$classroomId/$testId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/dashboard/approach'
    | '/dashboard/community'
    | '/dashboard/explorer'
    | '/dashboard/history'
    | '/dashboard/saved'
    | '/dashboard/search'
    | '/dashboard/teacher'
    | '/dashboard/'
    | '/dashboard/test/$classroomId/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approach': {
      id: '/dashboard/approach'
      path: '/approach'
      fullPath: '/dashboard/approach'
      preLoaderRoute: typeof DashboardApproachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/explorer': {
      id: '/dashboard/explorer'
      path: '/explorer'
      fullPath: '/dashboard/explorer'
      preLoaderRoute: typeof DashboardExplorerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved': {
      id: '/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/search': {
      id: '/dashboard/search'
      path: '/search'
      fullPath: '/dashboard/search'
      preLoaderRoute: typeof DashboardSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/test/$classroomId/$testId': {
      id: '/dashboard/test/$classroomId/$testId'
      path: '/test/$classroomId/$testId'
      fullPath: '/dashboard/test/$classroomId/$testId'
      preLoaderRoute: typeof DashboardTestClassroomIdTestIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardApproachRoute: typeof DashboardApproachRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardExplorerRoute: typeof DashboardExplorerRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
  DashboardSearchRoute: typeof DashboardSearchRoute
  DashboardTeacherRoute: typeof DashboardTeacherRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTestClassroomIdTestIdRoute: typeof DashboardTestClassroomIdTestIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApproachRoute: DashboardApproachRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardExplorerRoute: DashboardExplorerRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardSearchRoute: DashboardSearchRoute,
  DashboardTeacherRoute: DashboardTeacherRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTestClassroomIdTestIdRoute: DashboardTestClassroomIdTestIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
